/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thogakade_new.view;

import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import thogakade_new.Controller.PlaceOrderController;
import thogakade_new.Model.Customer;
import thogakade_new.Model.Item;
import thogakade_new.Model.OrderDetail;
import thogakade_new.Model.Orders;

/**
 *
 * @author ranga
 */
public class mainGui extends javax.swing.JFrame {

    private double totalPrice;

    /**
     * Creates new form mainGui
     */
    public mainGui() {
        initComponents();
        setOrderID();
        setDate();
        cusIdComboBox();
        setItemComboBox();


    }

    private void setDate() {
        dateField.setText(java.time.LocalDate.now().toString());
    }

    private void setItemComboBox() {
               ArrayList itemIdList = PlaceOrderController.getItemId();
               for(Object id : itemIdList){
                   comboBoxItm.addItem((String) id);
               }
    }

    private void setOrderID() {

        try {
            lblOrderId.setText(PlaceOrderController.getOrderID());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    private void cusIdComboBox() {
        try {
            ArrayList customerIdList = PlaceOrderController.getCusId();
            for(Object Id:customerIdList){
            comboBoxCus.addItem((String)Id);
        }
        } catch (SQLException ex) {
            Logger.getLogger(mainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    private int isAlreadyExists(String code) {
        DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
        
        for(int i=0; i<tblCart.getRowCount();i++ ){
            String tempCode = (String)dtm.getValueAt(i, 0);
            if (tempCode.equals(code)) {
                return i;
            }
        }
        return -1;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboBoxCus = new javax.swing.JComboBox<>();
        btnNewCus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboBoxItm = new javax.swing.JComboBox<>();
        txtFieldQty = new javax.swing.JTextField();
        txtFieldDsc = new javax.swing.JTextField();
        txtFieldPrice = new javax.swing.JTextField();
        txtFieldQtyOnHand = new javax.swing.JTextField();
        btnRemoveOdr = new javax.swing.JButton();
        btnAddOdr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lbl2 = new javax.swing.JLabel();
        btnPlaceOdr = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(804, 627));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("Place Order  Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 200, 32);

        lblOrderId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lblOrderId);
        lblOrderId.setBounds(120, 80, 70, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Qty");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 200, 40, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Order ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 70, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Order ID :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 80, 70, 30);

        dateField.setEditable(false);
        dateField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dateField);
        dateField.setBounds(600, 80, 140, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Order Date :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 80, 90, 30);

        comboBoxCus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxCusItemStateChanged(evt);
            }
        });
        comboBoxCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCusActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCus);
        comboBoxCus.setBounds(130, 130, 76, 26);

        btnNewCus.setText("New");
        btnNewCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCusActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewCus);
        btnNewCus.setBounds(220, 130, 80, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Customer ID :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 130, 100, 30);

        lblCustomerName.setText("Niroth");
        getContentPane().add(lblCustomerName);
        lblCustomerName.setBounds(610, 140, 90, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Customer Name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 130, 120, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Code :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 200, 120, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Description :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 200, 90, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Unit Price ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 200, 70, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Qty. on Hand");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 200, 100, 30);

        comboBoxItm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxItmItemStateChanged(evt);
            }
        });
        getContentPane().add(comboBoxItm);
        comboBoxItm.setBounds(30, 240, 76, 26);
        getContentPane().add(txtFieldQty);
        txtFieldQty.setBounds(660, 240, 120, 30);

        txtFieldDsc.setEditable(false);
        getContentPane().add(txtFieldDsc);
        txtFieldDsc.setBounds(170, 240, 160, 30);

        txtFieldPrice.setEditable(false);
        getContentPane().add(txtFieldPrice);
        txtFieldPrice.setBounds(370, 240, 120, 30);

        txtFieldQtyOnHand.setEditable(false);
        getContentPane().add(txtFieldQtyOnHand);
        txtFieldQtyOnHand.setBounds(520, 240, 120, 30);

        btnRemoveOdr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveOdr.setText("Remove");
        btnRemoveOdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOdrActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveOdr);
        btnRemoveOdr.setBounds(390, 300, 100, 30);

        btnAddOdr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddOdr.setText("ADD");
        btnAddOdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOdrActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddOdr);
        btnAddOdr.setBounds(280, 300, 100, 30);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Description", "Qty", "Unit Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCart);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 360, 720, 160);

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(204, 0, 0));
        lbl2.setText("0.0");
        getContentPane().add(lbl2);
        lbl2.setBounds(70, 550, 70, 25);

        btnPlaceOdr.setText("Place Order");
        btnPlaceOdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOdrActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOdr);
        btnPlaceOdr.setBounds(659, 550, 110, 26);

        jButton2.setText("commit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 550, 75, 26);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(204, 0, 0));
        lblTotal.setText("Total :");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(10, 550, 70, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void comboBoxCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCusActionPerformed

    private void btnNewCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCusActionPerformed
        // TODO add your handling code here:
        new AddCustomer().setVisible(true);
    }//GEN-LAST:event_btnNewCusActionPerformed

    private void btnPlaceOdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOdrActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
        ArrayList<OrderDetail> orderDetailList = new ArrayList<>();
        for(int i=0; i<tblCart.getRowCount();i++){
            OrderDetail orderDetail = new OrderDetail(lblOrderId.getText(),dtm.getValueAt(i, 0).toString(),(int)dtm.getValueAt(i,2 ),(double)dtm.getValueAt(i, 3));
            orderDetailList.add(orderDetail);
        }
        Orders orders = new Orders(lblOrderId.getText(),dateField.getText(),(String)comboBoxCus.getSelectedItem(),orderDetailList);
        
        try {
            boolean isupdated = PlaceOrderController.orderPlaced( orders);
            if(isupdated){
                JOptionPane.showMessageDialog(null, "done");
                dispose();
                new mainGui().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Fail");
                dispose();
                new mainGui().setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPlaceOdrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboBoxCusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxCusItemStateChanged
        
        String selectedCusId = comboBoxCus.getSelectedItem().toString();
        Customer customer = PlaceOrderController.getCustomer(selectedCusId);
        lblCustomerName.setText(customer.getName());

    }//GEN-LAST:event_comboBoxCusItemStateChanged

    private void comboBoxItmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxItmItemStateChanged
        String selectedItemCode = comboBoxItm.getSelectedItem().toString();
        Item item = PlaceOrderController.getItem(selectedItemCode);
        
        txtFieldDsc.setText(item.getDesc());
        txtFieldPrice.setText(item.getPrice().toString());
        txtFieldQtyOnHand.setText(String.valueOf(item.getQtOnHand()));
    }//GEN-LAST:event_comboBoxItmItemStateChanged

    private void calculateTotal() {
        DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();

        double total = 0;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += (double) dtm.getValueAt(i, 4);

        }
        lbl2.setText(String.valueOf(total));
    }
    private void btnAddOdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOdrActionPerformed
        
       
        DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
        
        int qty = Integer.parseInt(txtFieldQty.getText());
        double price=Double.parseDouble(txtFieldPrice.getText());
        double total = qty*price;
        int row = isAlreadyExists(comboBoxItm.getSelectedItem().toString());
        
        if(row== -1){
            Object[] rowData={
               comboBoxItm.getSelectedItem().toString(),
               txtFieldDsc.getText(),
               qty,
               price,
               total
            };
            
            dtm.addRow(rowData);
        }else{
            qty +=(int) dtm.getValueAt(row, 2);
            total += qty*price;
            
            tblCart.setValueAt(qty, row, 2);
            tblCart.setValueAt(total,row,4);
        }
         calculateTotal();
    }//GEN-LAST:event_btnAddOdrActionPerformed

    private void btnRemoveOdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOdrActionPerformed

        DefaultTableModel dtm = (DefaultTableModel)tblCart.getModel();
        int selectedRow = tblCart.getSelectedRow();
        dtm.removeRow(selectedRow);
        calculateTotal();
    }//GEN-LAST:event_btnRemoveOdrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOdr;
    private javax.swing.JButton btnNewCus;
    private javax.swing.JButton btnPlaceOdr;
    private javax.swing.JButton btnRemoveOdr;
    private javax.swing.JComboBox<String> comboBoxCus;
    private javax.swing.JComboBox<String> comboBoxItm;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtFieldDsc;
    private javax.swing.JTextField txtFieldPrice;
    private javax.swing.JTextField txtFieldQty;
    private javax.swing.JTextField txtFieldQtyOnHand;
    // End of variables declaration//GEN-END:variables
}
